# Sử dụng image Go chính thức làm base image
FROM golang:1.23 AS build


# Đặt thư mục làm việc trong container
WORKDIR /app

# Sao chép go.mod và go.sum vào container
COPY employee-management/go.mod employee-management/go.sum ./

# Chạy go mod tidy để cài đặt dependencies
RUN go mod tidy

# Sao chép tất cả mã nguồn còn lại vào container
COPY employee-management/ .

# Biên dịch ứng dụng Go
RUN go build -o main .

# Chạy ứng dụng Go
CMD ["./main"]
