FROM golang:1.20

# Set up working directory
WORKDIR /app

# Copy files
COPY . .

# Install dependencies
RUN go mod tidy

# Build the application
RUN go build -o main .

# Expose the application port
EXPOSE 8080

# Command to run the application
CMD ["./main"]
